language: java
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
script:
  - ./mvnw clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)